[package]
name = "ucui"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
crossterm = "0.28.1"
ratatui = "0.29.0"
shakmaty = "0.27.2"
shakmaty-uci = "0.1.1"
tui-big-text = "0.7.0"
uci = "0.2.1"
