import { Move } from "../lib/ucui/types";

export const startingLegalMoves: Move[] = [
  {
    _tag: "Normal",
    role: "Pawn",
    from: "A2",
    capture: null,
    to: "A3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "A2",
    capture: null,
    to: "A4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Knight",
    from: "B1",
    capture: null,
    to: "A3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Knight",
    from: "B1",
    capture: null,
    to: "C3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "B2",
    capture: null,
    to: "B3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "B2",
    capture: null,
    to: "B4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "C2",
    capture: null,
    to: "C3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "C2",
    capture: null,
    to: "C4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "D2",
    capture: null,
    to: "D3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "D2",
    capture: null,
    to: "D4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "E2",
    capture: null,
    to: "E3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "E2",
    capture: null,
    to: "E4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "F2",
    capture: null,
    to: "F3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "F2",
    capture: null,
    to: "F4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Knight",
    from: "G1",
    capture: null,
    to: "F3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Knight",
    from: "G1",
    capture: null,
    to: "H3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "G2",
    capture: null,
    to: "G3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "G2",
    capture: null,
    to: "G4",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "H2",
    capture: null,
    to: "H3",
    promotion: null,
  },
  {
    _tag: "Normal",
    role: "Pawn",
    from: "H2",
    capture: null,
    to: "H4",
    promotion: null,
  },
];
